apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJWTlPTWlMUklLWEF3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBek1qVXhOelExTkRKYUZ3MHpOREF6TWpNeE56VXdOREphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURxeDNsallMQlRCWHFXb3laa1dlNy9TbklGelJlcGVEb2drRjRTMXEzY0MxWVRyMVd4c0xPSTl4bzgKUW9JSDByMWlCT1ZsUzEwNzVwRW9JME96SGk2WUxHSmF1N0N4ZVNnUEhEVmF1YlJOZG1PZVYweHJlbXZKdmVqZAo3ODFzU1dJc1EvWnBoazkwdWx2WVlBaGl3ajVEL1JmV2txN21TVXBmNy9xdVRlODBaS2tjbzhnVHZ5bkxSNFJNCjFIM0Z2cTRLT0YrRlgwSnRkOEd0dDFnRWVYSVJMbUczUVVTZDh5YUNMSmJ5RkNwUFhuTUpkL3dJU3A3MkhORVUKS1NBUDdVQWIzL2JEWnhOUHRmV0lkbWsySTNFa0dtejN3dDRlYVZsL3E1NGprNTN6UFdMMGpxdXB0dFloOFpWRApMKzZQM1R6VVFJMVZGNUlwM1VZSG0zTjExNHAzQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTTDI4K08wQ0NlS1dvU0haVjFFeFdaYmp1MXZqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ1FzTVI3VU4waApIalc1UU1ZSlVReWk4ZExLVFBZWGJnRGZNMkJseWRFU1JRZ1JGYUdFekJ0RUxLSWM5SlQ1V3NYQWZZN1dxTEpICmdERjM3MDdEaFZDaTRvbHVIazRVYmxEU1oyUXEwSE5JZkVmT0NBUlJVQ1pWTlFyaUQ3OExnTWVJaVpyMyt0S0EKTG44T256TUdTWjlXY1JoTkthd2IvcGxVTkVJcHo2Zyt5c0YwNEI4SVlXSG5QZlpnWnRaN1IvQ2JRWHJ2NThrOApHRm5pVytmenRHaVQyT0k2OVpxNmdzOU5WRHZZcEZSRDRjb0hEalNoRFpwdDlSM3pOZ3Vub1hIYzZNTmZqTWhDCm1zaTA4YUNzT09OL3ZuRWxuQ1BBTUlNUlIrVmx2Q21RSHJYemg0Q29QaEhSMWlSZUxYK29PeXhRZXRJUWhjZHcKSndOelRzYlZlSjd1Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://02B73AC1C7F1B499FB1CD4C351255DBF.gr7.us-east-2.eks.amazonaws.com
  name: arn:aws:eks:us-east-2:771371893023:cluster/RayCluster
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJT21hMGUxeEpUVDR3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBek1qQXlNalExTkRKYUZ3MHpOREF6TVRneU1qVXdOREphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUN4akZKTkFIYitRTFZ4SDVyTGEzVFdMcFFEb2ZWNkhqZURPTTVhVUg3aEMyWXZpODVSWW9mWHhSU3cKZFllMGt5RjhUczZlQkpvbVRRcDhsQ1VsSTVyOG0vazh1VzM5TnA5MVV6dE0zNmw4MU5SWmo2eHlUYWQzZXdGNAprcEJ0aC9RWlhNU2hQWlg4NU5GY2U0c3NFdkF3alFaNGVEVzluREpsREVxaTNDWGxiMkV2NGg1SGMvYnJ3UkdVCmtqVnVBeDE4NjZLU3dNUUorRHJ0YW4zT1k0Q3hkU0gzRVpyT3Y3c1RrblNwOVpsbGFCM3hEQnBNMWdGVlpHalkKUW5zaDJnZFBnSlhYK1MxUFlqelB1U2pmQVUyMGpjSzF3NEJpbFlucW9DREZIbDEwRWtVc2Q0cHRjVXFUU3RuZQpqb3Y5alJuK1UrcDdjYXA4MWVxdFpJODZTazdiQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRZnE0M3dmN2M5ajlQZHkvcnFFV0EycURjVTBUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQmErZnF3NWd2Ygo3M0RZSSttNnNxbkpxUUJ6T1MwZ2FObU1XREpXMDZXeERyUUdWbVRFNzRDWlE5SE5DdzhuTHNRaE1HZklOZHdXClhBYVh5L2JvZGpEV1NORmFuWW9UeEFwLzVSVFprK0dGVVg3cmZnRW5GbklXelljVVBiZE53WHJCcmd3L3kzRGIKaExXMUNYczBtbVVnSHJYci9yd1MxVi94U3ZmUzQzUldXMzgxTk5OVW9UOHJXRWdNTTE5QTlNVnNYbFozcDdqNQpQNVRvMDc0SkI2VTFUazU4czRmT3ZiZ2hIN0pJMmdvc29TdnVnWTdCZzVmWTJVdW1jUDdNaUpUM2JxY1U4YlJiCm1xT0p0UFQ2elNUWG8rSEVmcHF5dzJUZjhuZmdJME9ndzlJeEV2UXNQdFN2dWQ5ck5LM1IzaUZxSDRTeEhIbmoKakJzODVaalgvV2NQCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://444885081CE769711FFFB1FA1C4EA567.yl4.us-east-2.eks.amazonaws.com
  name: my-cluster.us-east-2.eksctl.io
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJYVprUDArRHFqU3d3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBMk1qVXlNakF6TXpCYUZ3MHpOREEyTWpNeU1qQTRNekJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUQ1SDdpcU00OVdtWWd5ekJHbnFaZUhBa2dFUDJYdHRYbnFIQS9OeUVETUZNMlNKWmxxc2Y3ZFZRTTgKMWhBWG1tL0dQTmhUTE5RRjV2MkhlbUJKSzlZUmhPbGdPN0VIZ3JGYm1MU09QWjZBSWZTWTArM1MzN3VKR1MxdAovZ2JmbkVndTlyWUVEelV4TkhEQzdDdTJvTDJTbU53VjJxaGFCQzc3Z3ZIUDBJb0NTNEJxMDAwQ3pzYzRrbldvCmVxbjlSNFJ6Wmprd1dmUDBpb0xnNGhvazdEWVh0WndjbGRhTmJRRG5KMUxWZXRoekRpcjB0eWQ4VnlUYzZyNlkKeWgyNHNYRnhBcWRDYUxxWmttK2U3d3RyUjZ6TnlpR0o2RGN4QlRoQkZUU3lxd3pQYi8yREg2Um84Mnczck9TSApBZ0NPalRDQTJOYWhJc3d4ZVYwa2pDS09xaC9YQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTbU9MRWtCcEpGUGRKYk9QYjhhbWZYcHJuN1VEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRREVrdU9OdE9KWApaamZzbXQ5Q0ZWTTg5aHBLNENIWU94M2N3N2lQS1J6Y1ppRzFVK3lQZDRZMEZaZUFvcGk0Nm02ZkNSeGpwT3JlCnVtWlNHN1VCWjhqYlJJaDBpNEk1dFc1ZktCdkdyUlZrMUg3SmlRVE83KzArR3hZeDdTQ2F1NmZVUmZWMGlETmcKSzBIb2xQdFljQ1IzUzFoWVFWYnhGRHg4eVh4RlA5UzNkMmN3LzNIRmo5M055K0hCN0xXOWt1ZEpSbElnV0NYNApvR0Z2WmFTUjVNT3NyNmUvUUZ5dEVMUFVkSmlrNjQwSGxFQTZRdjdka1dnYVd3cXFyYkJCc2FqMkI4aXlrWGkzCk5OWXBtUDZsdGdVajBjMUZXRGJuUmpVZU9UYnhERFhJTnVZRWVrNUV2L24rNVNoN20weng1Zll5VS94WHIweXUKRTB1UHNvbVduZmpwCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://ED0108A768F7AF86A9F9EC156194EE7A.gr7.us-east-2.eks.amazonaws.com
  name: arn:aws:eks:us-east-2:771371893023:cluster/standardCluster
contexts:
- context:
    cluster: arn:aws:eks:us-east-2:771371893023:cluster/RayCluster
    user: arn:aws:eks:us-east-2:771371893023:cluster/RayCluster
  name: arn:aws:eks:us-east-2:771371893023:cluster/RayCluster
- context:
    cluster: my-cluster.us-east-2.eksctl.io
    user: venkatajagannath.yellapragada@astronomer.io@my-cluster.us-east-2.eksctl.io
  name: venkatajagannath.yellapragada@astronomer.io@my-cluster.us-east-2.eksctl.io
- context:
    cluster: arn:aws:eks:us-east-2:771371893023:cluster/standardCluster
    user: arn:aws:eks:us-east-2:771371893023:cluster/standardCluster
  name: arn:aws:eks:us-east-2:771371893023:cluster/standardCluster
current-context: arn:aws:eks:us-east-2:771371893023:cluster/standardCluster
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-2:771371893023:cluster/RayCluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-2
      - eks
      - get-token
      - --cluster-name
      - RayCluster
      - --output
      - json
      command: aws
      env:
      - name: AWS_PROFILE
        value: MyProfile
      interactiveMode: IfAvailable
      provideClusterInfo: false
- name: venkatajagannath.yellapragada@astronomer.io@my-cluster.us-east-2.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - token
      - -i
      - my-cluster
      command: aws-iam-authenticator
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      - name: AWS_DEFAULT_REGION
        value: us-east-2
      interactiveMode: IfAvailable
      provideClusterInfo: false
- name: arn:aws:eks:us-east-2:771371893023:cluster/standardCluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-2
      - eks
      - get-token
      - --cluster-name
      - standardCluster
      - --output
      - json
      command: aws