{
  "apiVersion": "v1",
  "clusters": [
    {
      "cluster": {
        "certificate-authority-data": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJTU92NDJ5MHFQNTR3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBMk1qVXhOalEwTlRSYUZ3MHpOREEyTWpNeE5qUTVOVFJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURNYVRsQWxHQm10clA0TytmSHRaYWFFeUdISCtWVEVPdkE0cTB4dTBGRHRROHI3Y0ZZdzJxWHQ0d2kKa3hWQ1V2WC9JUjlKYlFpbW52dlIybXFHUWwzWDhTWWxoYUNNWldlbDR4anhFamJwZFVzYW1xUkkvNTNxMDl0SgpNQjl4dEtuZFNpdnRETU9uT09PTkh4STl5Y3AwcmgxZFI2OFRtNkFudStRazRJWXM4RUpCVytTUG1FLzBnVVhXCmFjYjVwZ0cwRzMrTFBlZElNOEQ4MTdXaXlQZSs0eVI1MkVQMjJUY3lhMUo5ZnJrU2UvdmsvK3FJUEZlSjc5YnQKWGJQTVQzRldBemRNVlZQeHZwcUwwT01DcktnbFRwZVBMRzFZM0x1RlBvU2lRNHd6RmlGd3pnL3AzemN4OUVFRgpkUWR4UDFIK3lMSU9hODNXOERxQ3NrendiWDZUQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUcjFNeUJoLzE5M1lRbjliSWM1SG9pMnN0c1JEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkZOekdTOURsZgo2T2wzTjY2SnVWUUZaUWg4ZUc1Z0JHVVdyZHYwT2JOdmRFZGZKUjlCUnhITlNTSEQzZFZneEJFdm9YUjQvOVJOCkZscHUycG13TW1ZUUNQTm5UQnZOTlpjSnN4bEFMZlpKYXhRdENnV3BDL05EeE5JUnpuWTAvMFBIbnJZSUd4OTQKa01sbVhYbXlVVWF4RTFrckJlay9NMHQyUnpZaGpXc01oWTQvUEdUWnRqRkxscUZKUEhwWXpYNlRCNkdSaU05UwpSTzE0TVRHNWQ3M0RaUENad1B3NktvekxEazdTbVJXNlBLS2NmU2FjS2svejhOeUdReC9DdEgxS25mYzJYeUJXClpha1hucTNDMUFlbnhZVjMwYkNBditTcmhSekJXQ2szQXUzNW11aWZKb1FVMjg0Qkx0bnhETkRDTkgwdm91UUQKQW9wRno4K216eTVwCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K",
        "server": "https://03D6E1D5792DBC91D97A91094EEF9869.gr7.us-east-2.eks.amazonaws.com"
      },
      "name": "RayCluster.us-east-2.eksctl.io"
    }
  ],
  "contexts": [
    {
      "context": {
        "cluster": "RayCluster.us-east-2.eksctl.io",
        "user": "venkatajagannath.yellapragada@astronomer.io@RayCluster.us-east-2.eksctl.io"
      },
      "name": "venkatajagannath.yellapragada@astronomer.io@RayCluster.us-east-2.eksctl.io"
    }
  ],
  "current-context": "venkatajagannath.yellapragada@astronomer.io@RayCluster.us-east-2.eksctl.io",
  "kind": "Config",
  "preferences": {},
  "users": [
    {
      "name": "venkatajagannath.yellapragada@astronomer.io@RayCluster.us-east-2.eksctl.io",
      "user": {
        "exec": {
          "apiVersion": "client.authentication.k8s.io/v1alpha1",
          "args": [
            "token",
            "-i",
            "RayCluster"
          ],
          "command": "aws-iam-authenticator",
          "env": [
            {
              "name": "AWS_STS_REGIONAL_ENDPOINTS",
              "value": "regional"
            },
            {
              "name": "AWS_DEFAULT_REGION",
              "value": "us-east-2"
            }
          ],
          "provideClusterInfo": false
        }
      }
    }
  ]
}