apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJTUY1MTFKOThzeTB3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBMk1qTXdNREF3TXpkYUZ3MHpOREEyTWpFd01EQTFNemRhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUM2MVJjMTBHWlB2ZERVbUpxakZlRHBIQkZGREJZengyenQ4SmNHM2xVQ3BmaXVCd2g5VFY5KytUM08KQnhzeGxvY3p5Q2VMTVByd0lSUiswdmlIY2N2b3U3V2NFOTdTR0tmZ0hKdXV2UWhLaW8vbnBGd0htQVpoVFYraApNSElKcVNjbXZCQlM1eHpJZVVYbEFiMVkwSjU2em5OeHcwVDE1SnF5RkgrelhwamI1VTZMc0dFazlzZkM3d2tpCnMrUTlHTkZpMkVUVlFGbmltTWdRdlo2YlZ5NWpXN3gyVkE1UFRoalhEMkpRVnBMTHhiUjRGaU14TEJFRVYyME0KVEVQTW5nQ0VRSFlEM0JRWURuNDFQdXE4b1dVRGRxTEFsdk5xTkpldzNPeGZzVVVnbXNvM0E3RGwzQmpHeC96RwpJc0Z4N3NHc2kzbWd3K2pveXJmV0todWNkZTVMQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUVG1BWU9PbENUbEoxbVV2YnM4L1lmaVpjc0FUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQmhwTjhLN3gwYQpHRXVPdTluS3Rnd0RQc00wTE8vZ3NSc0pSdnlLSVptQkdQYUE2a3VwZVd4N1duSHZQT2NmSnlMQlppZ3hHdGFXClMrZW51dGVidGxJTDdMTS91OVMyc2pINHVyMC93QmltZkFvTHVrbjBPQ09Ga2w1cWUySm1INXU5RHhrNFIrR3YKMmtKSHRtY3NUM1czUGhaOU5WeFdhMEhucUdqMTZuYjhMcU5BMUxNSktidXM0WGtJMk1CNC9VVnMxNVd1Y2RERQpPR3VnMnhxcG13M2cyK2dHcUREL0JRYnp2VXdDY2RkbDBOWmxwL0dodXRIQkNNODRzN213ODZ5MkJ0UlJPY2c5CkNNVDhQdlNyNGFIa3ZveENDdnNrdFpsaU4wTUhMQWlmU3Z4eGRXY2IwWGs2MnJGdGZNVnVXSFJuS3llbDNBdXAKbTZCVXdFL2JsUUxrCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://01D51FAB1E5A9E866BFDDB204A3D7C75.gr7.us-east-2.eks.amazonaws.com
  name: RayCluster.us-east-2.eksctl.io
contexts:
- context:
    cluster: RayCluster.us-east-2.eksctl.io
    user: venkatajagannath.yellapragada@astronomer.io@RayCluster.us-east-2.eksctl.io
  name: venkatajagannath.yellapragada@astronomer.io@RayCluster.us-east-2.eksctl.io
current-context: venkatajagannath.yellapragada@astronomer.io@RayCluster.us-east-2.eksctl.io
kind: Config
preferences: {}
users:
- name: venkatajagannath.yellapragada@astronomer.io@RayCluster.us-east-2.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - token
      - -i
      - RayCluster
      command: aws-iam-authenticator
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      - name: AWS_ACCESS_KEY_ID
        value: ASIA3HGKZAEPRUMQT6IO
      - name: AWS_SECRET_ACCESS_KEY
        value: 7p1ebNBrqyVkiUrEiVo4WQCEWwewDkBuEAOFi9P/
      - name: AWS_SESSION_TOKEN
        value: IQoJb3JpZ2luX2VjENX//////////wEaCXVzLWVhc3QtMiJHMEUCIQCig3LWGQbCiz6zf62HWI5qDbwSYx+nA4ZCPSYW+IME1QIgLIuA1FsTXm30179ecmRIYbpe66oxBGZYgmIGV6XYTcsqtQMIfxAAGgw3NzEzNzE4OTMwMjMiDIWZv8aaP+rJJtQD8CqSA26AXxcObUhvISosgbHrlWHAegW744jnm8/AZ+wDqMwd3DL2M3UEvvLYY1tLpAc8fiW87fj8f2cUVLX3AWKFSo1E1Bc7DYZ0vZiBeU90h0YdaNgBmo8P8H5usSQ/xWZK2aFgsXOxBjD6GWmdC2kg5DLhUS9PutU1qMFoBD5IZOGHeNWdnGXG7dZPvaMzycaJy4XINY4faD36k7Yzq9WzeLwxCH96Z8po27vI3bW8BOHmnKfV7tQEYyiVtoHz2hNsNMIrrsNmbIbgfjzp8eLM5kzRsepx8/7gStywJEJFn6lnuQt1vV9nhj12iNLbI7MfVo+mzyfsF6oe35YEVWZn8f4sBLDj0EZkuXGi2p7Q6LMs9i8b+pJGW7RDKCUS98Mhi/B6WfmoDE/anRBxFlBqmpjDPDllO3lglG1HDJbnk9+meCydhkRLJ4bbCoCH31z+S2qFFlaoUhb5Yo736M09qSVpa3ydgPoPsACVZ+S+GvORtKd7ysc34WSVXC3Ykn9WGUrT1eWXNxBZ+SHqO10DeB9cVjDFgt2zBjqmAad6xUORSfEoLvTI4jmx7BDUy3XqtDtbn8pI7v1GxZ27d6/xLokuIgiljgP8nfmp8oLZHQ38VRXKtyBd/TS7O0Bajkt3cfFVlRua4G49zdZ8hVOY4IxYKDGdcxisxhhgb+M2EW3XkyhJEmuThal2QIMO0eUiSqWuMgrdaCTd8jXGz30Vuvn3TlQOvtvIAaLapQMXUkG49/SucP8tgevfDcQaEHovo/Q=
      - name: AWS_DEFAULT_REGION
        value: us-east-2
      provideClusterInfo: false
