apiVersion: v1
kind: Service
metadata:
  name: ray-service
  namespace: ray
spec:
  selector:
    ray.io/cluster: raycluster-complete
    ray.io/node-type: head
  ports:
  - protocol: TCP
    port: 8265
    targetPort: 8265
  - protocol: TCP
    port: 10001
    targetPort: 10001
  type: LoadBalancer
