apiVersion: v1
kind: Service
metadata:
  name: ray-client-service
  namespace: ray
spec:
  selector:
    ray.io/cluster: raycluster-complete-head-svc
    ray.io/node-type: head
  ports:
  - protocol: TCP
    port: 10001
    targetPort: 10001
  type: LoadBalancer
