apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: raycluster-complete
spec:
  enableInTreeAutoscaling: true
  headGroupSpec:
    rayStartParams:
      block: 'true'
      dashboard-host: 0.0.0.0
    serviceType: LoadBalancer
    template:
      metadata:
        labels:
          ray-node-type: head
      spec:
        containers:
        - name: ray-head
          image: rayproject/ray-ml:latest
          resources:
            limits:
              cpu: 4
              memory: 8Gi
            requests:
              cpu: 4
              memory: 8Gi
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","ray stop"]
          ports:
          - containerPort: 6379
            name: gcs
          - containerPort: 8265
            name: dashboard
          - containerPort: 10001
            name: client
          - containerPort: 8000
            name: serve
          - containerPort: 8080
            name: metrics
          - containerPort: 44217
            name: as-metrics
          - containerPort: 44227
            name: dash-metrics # dashboard
  workerGroupSpecs:
  - groupName: small-group
    maxReplicas: 2
    minReplicas: 1
    rayStartParams:
      block: 'true'
    replicas: 1
    template:
      metadata: null
      spec:
        containers:
        - image: rayproject/ray-ml:latest
          name: machine-learning
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 1
              memory: 1Gi
